// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkagenBooking.Infrastructure.Persistence;

#nullable disable

namespace SkagenBooking.Infrastructure.Migrations
{
    [DbContext(typeof(SkagenBookingDbContext))]
    partial class SkagenBookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("SkagenBooking.Core.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly?>("EstimatedArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("GuestCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NeedsParking")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SkagenBooking.Core.Entities.ParkingAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ParkingAllocations");
                });

            modelBuilder.Entity("SkagenBooking.Core.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParkingCapacity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("SkagenBooking.Core.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "NightlyRate", "SkagenBooking.Core.Entities.Room.NightlyRate#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("NightlyRateAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("TEXT")
                                .HasColumnName("NightlyRateCurrency");
                        });

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("SkagenBooking.Core.Entities.Booking", b =>
                {
                    b.OwnsOne("SkagenBooking.Core.ValueObjects.DateRange", "DateRange", b1 =>
                        {
                            b1.Property<int>("BookingId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("CheckIn")
                                .HasColumnType("TEXT")
                                .HasColumnName("CheckIn");

                            b1.Property<DateTime>("CheckOut")
                                .HasColumnType("TEXT")
                                .HasColumnName("CheckOut");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.Navigation("DateRange")
                        .IsRequired();
                });

            modelBuilder.Entity("SkagenBooking.Core.Entities.ParkingAllocation", b =>
                {
                    b.OwnsOne("SkagenBooking.Core.ValueObjects.DateRange", "DateRange", b1 =>
                        {
                            b1.Property<int>("ParkingAllocationId")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("CheckIn")
                                .HasColumnType("TEXT")
                                .HasColumnName("CheckIn");

                            b1.Property<DateTime>("CheckOut")
                                .HasColumnType("TEXT")
                                .HasColumnName("CheckOut");

                            b1.HasKey("ParkingAllocationId");

                            b1.ToTable("ParkingAllocations");

                            b1.WithOwner()
                                .HasForeignKey("ParkingAllocationId");
                        });

                    b.Navigation("DateRange")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
